from __future__ import annotations

from agents.base import Agent
from state import ChangeSet, ProjectState


class FeatureAgent(Agent):
    def run(self, state: ProjectState) -> ChangeSet:
        content = (
            "# Feature Notes\n"
            f"Goal: {state.goal}\n"
            "Generated by FeatureAgent as a v0 placeholder.\n"
        )
        return ChangeSet(
            files={"FEATURE_NOTES.md": content},
            agent_name=self.name,
            token_used=350,
        )
