from __future__ import annotations

from agents.base import Agent
from state import ChangeSet, ProjectState


class RefactorAgent(Agent):
    def run(self, state: ProjectState) -> ChangeSet:
        content = (
            "# Refactor Suggestions\n"
            f"Tracked files: {len(state.files)}\n"
            "Generated by RefactorAgent as a v0 placeholder.\n"
        )
        return ChangeSet(
            files={"REFACTOR_NOTES.md": content},
            agent_name=self.name,
            token_used=150,
        )
