from __future__ import annotations

from agents.base import Agent
from state import ChangeSet, ProjectState


class TestAgent(Agent):
    def run(self, state: ProjectState) -> ChangeSet:
        content = (
            "# Test Plan\n"
            f"Covers current files: {', '.join(sorted(state.files.keys())) or 'none yet'}\n"
            "Generated by TestAgent as a v0 placeholder.\n"
        )
        return ChangeSet(
            files={"TEST_PLAN.md": content},
            agent_name=self.name,
            token_used=200,
        )
